feat: add proxy to validations (#102)
* feat: add proxy to validations

* docs: update usage of insecure

* feat: proxy: apply review items

* feat: proxy: update usage with flags, make error message compatible with regex so it can be communicated when there's a config err

* feat: proxy support: implement lib

* feat: proxy: fix userdata script

* feat: proxy: fix linting issue

* feat: proxy: add review items

* feat: proxy: handle the case when there's no cacert to be passed (no-tls)

diff --git a/pkg/helpers/config/userdata.yaml b/pkg/helpers/config/userdata.yaml
--- a/pkg/helpers/config/userdata.yaml
+++ b/pkg/helpers/config/userdata.yaml
@@ -2,12 +2,23 @@
 repo_update: true
 package_update: true
 packages:
-  - docker 
+  - docker
+write_files:
+  - path: /run-container.sh
+    permissions: 755
+    content: |
+      #!/bin/bash
+      # based on tls, set up docker run command.
+      if [[ "${CACERT}" != "" ]]; then
+        echo "${CACERT}" | base64 --decode > /proxy.pem
+        sudo docker run -v /proxy.pem:/proxy.pem -e "HTTP_PROXY=${HTTP_PROXY}" -e "HTTPS_PROXY=${HTTPS_PROXY}" --env "AWS_REGION=${AWS_REGION}" -e "START_VERIFIER=${VALIDATOR_START_VERIFIER}" -e "END_VERIFIER=${VALIDATOR_END_VERIFIER}" ${VALIDATOR_IMAGE} --timeout=${TIMEOUT} --cacert=/proxy.pem --no-tls=${NOTLS}  >> /var/log/userdata-output || echo "Failed to successfully run the docker container"
+      else
+        sudo docker run --env "AWS_REGION=${AWS_REGION}" -e "HTTP_PROXY=${HTTP_PROXY}" -e "START_VERIFIER=${VALIDATOR_START_VERIFIER}" -e "END_VERIFIER=${VALIDATOR_END_VERIFIER}" ${VALIDATOR_IMAGE} --timeout=${TIMEOUT}  >> /var/log/userdata-output || echo "Failed to successfully run the docker container"
+      fi
 runcmd:
   - sudo service docker start 2>1 > /dev/null || echo "docker not started by systemctl"
   - echo "${USERDATA_BEGIN}" >> /var/log/userdata-output
   - sudo docker pull ${VALIDATOR_IMAGE}
-  # Use `|| true` to ignore failure exit codes, we want the script to continue either way
-  - sudo docker run --env "AWS_REGION=${AWS_REGION}" -e "START_VERIFIER=${VALIDATOR_START_VERIFIER}" -e "END_VERIFIER=${VALIDATOR_END_VERIFIER}" ${VALIDATOR_IMAGE} --timeout=${TIMEOUT}  >> /var/log/userdata-output || echo "Failed to successfully run the docker container"
+  - /run-container.sh
   - echo "${USERDATA_END}" >> /var/log/userdata-output
   - cat /var/log/userdata-output >/dev/console
